apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume
  template:
    metadata:
      labels:
        app: volume
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
        - name: network-multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: multi-port
          volumeMounts:
            - mountPath: /opt
              name: shared-volume
          command:
            [
              "sh",
              "-c",
              "sleep 5 && while true; do cat /opt/output.txt; sleep 6; done",
            ]
        - name: busybox
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "while true; do echo $(date) > /test/output.txt; sleep 5; done",
            ]
          volumeMounts:
            - mountPath: /test
              name: shared-volume
